server:
  port: 8082

spring:

  application:
    name: bbc-post-service
    web:
      resources:
        static-locations: file:uploads/
  datasource:
    url: jdbc:mysql://localhost:3306/bbc_post_service?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: blossom913@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: mybookbooksecretkeymybookbooksecretkey

bbc-user-service:
  url: http://localhost:8081  # 실제 유저 서비스 포트